"""fixes

Revision ID: 786611f5aeec
Revises: 1e527b879b34
Create Date: 2026-04-04 19:42:06.348379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '786611f5aeec'
down_revision: Union[str, Sequence[str], None] = '1e527b879b34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('cover_url', sa.String(), nullable=True))
    op.add_column('user_achievements', sa.Column('achievement_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('user_achievements_achievment_id_fkey'), 'user_achievements', type_='foreignkey')
    op.create_foreign_key(None, 'user_achievements', 'achievements', ['achievement_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_achievements', 'achievment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_achievements', sa.Column('achievment_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_achievements', type_='foreignkey')
    op.create_foreign_key(op.f('user_achievements_achievment_id_fkey'), 'user_achievements', 'achievements', ['achievment_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_achievements', 'achievement_id')
    op.drop_column('lessons', 'cover_url')
    # ### end Alembic commands ###
