"""add_gestures_dictionary_and_favorites

Revision ID: 8ac8eb22faeb
Revises: 99020b077a63
Create Date: 2026-03-28 14:54:55.183334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ac8eb22faeb'
down_revision: Union[str, Sequence[str], None] = '99020b077a63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gestures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('gif_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gestures_id'), 'gestures', ['id'], unique=False)
    op.create_index(op.f('ix_gestures_name'), 'gestures', ['name'], unique=True)
    op.create_table('favorite_gestures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gesture_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gesture_id'], ['gestures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favorite_gestures_id'), 'favorite_gestures', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_favorite_gestures_id'), table_name='favorite_gestures')
    op.drop_table('favorite_gestures')
    op.drop_index(op.f('ix_gestures_name'), table_name='gestures')
    op.drop_index(op.f('ix_gestures_id'), table_name='gestures')
    op.drop_table('gestures')
    # ### end Alembic commands ###
